name: collectorapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  provider: ^6.1.5+1
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  get: ^4.7.3
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^10.0.0
  country_code_picker: ^3.0.0
  icons_launcher: ^3.0.3
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


icons_launcher:
  image_path: "assets/images/mahakal.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
